services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis_data:/data

  app:
    build: .
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    volumes:
      - ./nextcloud_data:/var/www/html
      # Mapeando suas pastas locais para dentro do contêiner
      - /mnt/Arquive:/mnt/Arquive
      - /mnt/Backup_Cripto:/mnt/Backup_Cripto:rshared
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - REDIS_HOST=redis

  cron:
    build: .
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
